---
generator_definitions:
  - name: widget_generator
    file_path: "widget_generator.py"
    targets: widgets
    query: widget_query
    class_name: WidgetGenerator
    parameters:
      name: "name__value"

queries:
  - name: widget_query
    file_path: "widget_query.gql"
# check_definitions:
#   - name: "check_color_tags_name"
#     class_name: "ColorTagsCheck"
#     file_path: "tags_check.py"

# queries:
#   - name: tags_query
#     file_path: "tags_query.gql"

# jinja2_transforms:
#   - name: my-jinja2-transform # Unique name for your transform
#     description: "short description" # (optional)
#     query: "tags_query" # Name or ID of the GraphQLQuery
#     template_path: "tags_tpl.j2" # Path to the main Jinja2 template
